{{ if .Values.imagePullSecrets }}
{{ if .Values.pullSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.pullSecretName}}
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace | quote }}
type: kubernetes.io/dockerconfigjson
data:
  {{ if .Values.pullSecretData }}
  .dockerconfigjson: {{.Values.pullSecretData}}
  {{ else }}
  .dockerconfigjson: {{ template "imagePullSecret" . }}
  {{ end }}
{{ end }}
{{ end }}
